### ISSUE TITLE
Brokercell reconcile not triggered by Broker Changes

### ISSUE THREAD

**Issue by ian-mi** [google/knative-gcp#1704] opened 2020-09-15 23:44 UTC
**Describe the bug**
Brokercell reconciles only happen on resync or change to the brokercell itself.

 **Expected behavior**
A brokercell reconcile should happen with each broker change.

 **To Reproduce**
Create a new broker and look for brokercell reconcilation log messages.

 **Knative-GCP release version**
master

**Comment by liu-cong** [comment] 2020-09-16 00:09
Possible duplicate of #1437

**Closed** 2020-09-16 00:36 UTC
Labels: area/broker, kind/bug
