### ISSUE TITLE
GCP Broker e2e  Performance Tests

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#929] opened 2020-04-23 16:47 UTC
**Problem**

There are already some examples in channel based broker. We should be able to reuse most of the components.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment] 2020-05-27 19:02
Duplicate of #981

**Closed by grantr** 2020-05-27 19:02 UTC
Labels: area/broker, area/performance, kind/feature-request, priority/1, release/2
