### ISSUE TITLE
Probe Helper stopped responding probe requests

### ISSUE THREAD

**Issue by liu-cong** [google/knative-gcp#1612] opened 2020-08-19 23:06 UTC
Need to run some stress test to reproduce.

I think the issue could be due to the concurrent map access. We should fix that.

**Comment by tommyreddad** [comment] 2020-08-20 21:04
There are a few problems with the probe helper.

### 1. The probe helper sender client is limited to waiting on 4 events

The CloudEvents client creates GOMAXPROCS(0) == 4 goroutines which concurrently handle events by way of the probe helper's `forwardFromProbe` function (which is blocking). Once the probe helper waits for 4 events, the CloudEvents client waits before handling any more events.

How to reproduce:
  1. Create a probe helper, a probe helper receiver service, a Broker, a Trigger targeting events of type `good-event` sinking to the probe helper receiver service.
  2. Send a CloudEvent of type `good-event` to the probe (success, return code 200)
  3. Send a CloudEvent of type `bad-event` to the probe (sender waits)
  4. Send a CloudEvent of type `good-event` to the probe (success, return code 200)
  5. Send a CloudEvent of type `bad-event` to the probe (sender waits)
  6. Send a CloudEvent of type `good-event` to the probe (success, return code 200)
  7. Send a CloudEvent of type `bad-event` to the probe (sender waits)
  8. Send a CloudEvent of type `good-event` to the probe (sender waits)

Relevant CloudEvents code snippet: https://github.com/cloudevents/sdk-go/blob/master/v2/client/client.go#L210-L242
Relevant probe helper blocking wait: https://github.com/google/knative-gcp/blob/d84f41947b8d2b3a3738886a6148a7d52a671a24/test/test_images/probe_helper/probe_helper.go#L53-L59

How to fix: A newer version of the probe helper only forwards events of a type which it recognizes, which can mitigate catastrophic failure, but a better solution is needed.

### 2. Concurrent access to the receivedEvents map is not safe

How to fix: Synchronize access to the receivedEvents map.

### 3. (Related to 2.) Race condition with multiple Triggers for same event

If multiple Triggers forward the same `event` to the probe helper, this can cause a race condition.
  1. The receiver handles the first event and sends `receivedEvent[eventID] <- true`
  2. The sender receives something in the channel and deletes it.
  3. The receiver handles the second event and attempts to send along the deleted channel `receivedEvent[eventID]`.

How to fix:
  * Don't have multiple Triggers forward the same event to the probe helper.
  * Always safely index into the receivedEvents map.
  * Make sure to clean old Triggers (or other obsolete resources) when updating cluster.

**Comment by grantr** [comment] 2020-09-09 03:54
Can this issue be closed? If not, let's move it to a current milestone.

**Comment by tommyreddad** [comment] 2020-09-09 14:19
The part of this issue dependent on our code has been fixed.

Otherwise, part of this issue was caused by a bug in the CloudEvents client, which has now been fixed and merged in the CloudEvents SDK master branch (https://github.com/cloudevents/sdk-go/pull/574) but not yet released. So I'm not sure how we should continue to track this issue, if we should keep it active until the next CloudEvents SDK release, or if we should patch the fix before then.

**Comment by grantr** [comment] 2020-09-29 19:57
I moved this back to the backlog. Has the fix we were waiting on in CloudEvents SDK been released yet?

**Comment by tommyreddad** [comment] 2020-09-29 21:18
It was released yesterday, I'll make a quick PR with the upgrade which should close this issue.

**Closed** 2020-10-01 15:18 UTC
Labels: kind/bug
