### ISSUE TITLE
Set the resource requests for the pubsub BrokerCell when creating the Broker resource.

### ISSUE THREAD

**Issue by upodroid** [google/knative-gcp#1671] opened 2020-09-09 10:22 UTC
**Problem**
The BrokerCell defaults to very high resource requests which is akward for development. It defaults to like 3.5 cores as a starting point which is overkill for development or learning purposes.

I had to tweak the Brokercell resource in the cloud-run-events namespace so some documentation on how to change it or the ability to set it when creating the broker resource.

**[Persona:](https://github.com/knative/eventing/blob/master/docs/personas.md)** 
Which persona is this feature for?
All

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.

**Time Estimate (optional):** 
Don't know

**Additional context (optional)**
Add any other context about the feature request here.

**Comment by grantr** [comment] 2020-10-06 17:04
Duplicate of #1696

**Closed by grantr** 2020-10-06 17:04 UTC
Labels: area/broker, kind/feature-request, priority/1, release/2

**Comment by grantr** [comment] 2020-10-06 22:20
I think this is actually 3 requests:
- Document how to alter the BrokerCell resource requirements. This is tracked in #1696.
- Make the BrokerCell resource requirements editable before creating a Broker. Tracked in #1811.
- Reduce the shipped resource requirements to be more appropriate for dev clusters. Tracked in #1812.
