### ISSUE TITLE
Distinct ServiceAccounts

### ISSUE THREAD

**Issue by Harwayne** [google/knative-gcp#77] opened 2019-07-01 21:19 UTC
The current ServiceAccount name for the controller is `controller`. This works well while in the `cloud-run-events` namespace. But we saw in knative/eventing that people wanted to install the controllers and webhooks into user defined namespaces, at which point the name `controller` is likely to collide. 

I recommend `cloud-run-events-controller`.

**Comment by n3wscott** [comment] 2019-07-08 20:17
This is working as intended.

**Comment by akashrv** [comment] 2019-10-08 16:29
@Harwayne @n3wscott Is this fixed or won't fix the issue? Is it still an open issue?

**Comment by Harwayne** [comment] 2019-10-08 16:32
This is a design question. My view is that the ServiceAccount names should be moderately unique regardless of which namespace they are in, as I think that in the future it may be common for people to install in non-standard namespaces. @n3wscott prefers the simplicity and brevity of the 'non-qualified' name, because in his view the namespace itself gives all the necessary qualifications.

**Comment by akashrv** [comment] 2019-10-08 17:45
@mattmoor @vaikas-google This is more of a "best practice" question. Could you resolve this as TLs for knative and comment your decision?

**Comment by evankanderson** [comment] 2019-10-08 19:23
This doesn't seem like a Knative question, given that this is in the "Google" repo.

Having a hard-coded ServiceAccount name seems like a bit of a smell to me. I suspect you want to make this configurable, and then ship with a sensible default with the following priorities:

1. Not incredibly insecure (e.g. don't ship with a shared secret in code, or permitting unauthenticated read/modify/write for internet-connected components.
1. Works out of the box for new users.
1. Easy to understand for people unfamiliar with the system.
1. Minimum privilege and strong compartmentalization.

You should definitely document how to set up minimum privilege and strong compartmentalization, but I'd design first for a good new-user out of box experience.

**Closed** 2020-03-02 23:47 UTC
Labels: kind/cleanup, triage/wont-fix
