### ISSUE TITLE
Python samples for https://github.com/google/knative-gcp/tree/master/docs/pullsubscription

### ISSUE THREAD

**Issue by dkozlov** [google/knative-gcp#452] opened 2019-12-17 23:17 UTC
**Problem**
Python implementation of https://github.com/knative/eventing-contrib/blob/master/cmd/event_display/main.go? I have found https://github.com/elegantmonkeys/python-kncloudevents/tree/master/examples/event_display but seems that it does not work with PullSubscription(https://github.com/google/knative-gcp/tree/master/docs/pullsubscription )

**Exit Criteria**
A measurable (binary) test that would indicate that the problem has been resolved.
https://github.com/google/knative-gcp/tree/master/docs/pullsubscription working with python implementation of event_display.py

**Time Estimate (optional):** 
How many developer-days do you think this may take to resolve?
Do not know

**Additional context (optional)**
Add any other context about the feature request here.
 I am using python for my knative services and there is no examples how to receive message from knative:Subscription and knative:Topic by python function using cloudevents.

**Comment by nachocano** [comment] 2020-03-02 22:22
Not sure if this actually belong here. We are not adding python examples in this repo. 
I'm wondering why PullSubscription doesn't work. Maybe the python event_display doesn't support CloudEvents v1.0?

BTW, instead of PullSubscription, you should be able to leverage [CloudPubSubSource](https://github.com/google/knative-gcp/blob/master/docs/examples/cloudpubsubsource/README.md) now.

**Comment by nachocano** [comment] 2020-03-03 02:22
Closing this one... We won't be adding python examples here. 
I think the correct place to file this issue is in the https://github.com/elegantmonkeys/python-kncloudevents/ repo. 
I think the problem is that they do not support CloudEvents v1 yet (or at least at the time that this bug was filed).

**Closed by nachocano** 2020-03-03 02:22 UTC
Labels: kind/feature-request, triage/wont-fix
