### ISSUE TITLE
Make broker component HPA parameters configurable (with brokercell)

### ISSUE THREAD

**Issue by yolocs** [google/knative-gcp#1250] opened 2020-06-09 16:41 UTC
Scenarios:
1. A user might want to adjust the HPA parameters according to their usage.
2. In perf test, we might want to "disable" HPA. Related to https://github.com/google/knative-gcp/pull/1195

**Comment by grantr** [comment] 2020-07-22 18:18
Fixed by #1379. Duplicate of #1300.

**Closed by grantr** 2020-07-22 18:18 UTC
Labels: area/broker, priority/1, release/2
